version: '3'

services:
  fornax-db:
    image: postgres:10.4
    volumes:
      - fornaxdb:/var/lib/postgresql/data/
  fornax-web:
    build: .
    entrypoint: /code/entrypoint.sh
    environment:
      - APPLICATION_PORT=${APPLICATION_PORT:-8003}
    volumes:
      - .:/code
    ports:
      - "${APPLICATION_PORT:-8003}:${APPLICATION_PORT:-8003}"
    depends_on:
      - fornax-db

volumes:
  fornaxdb:
