version: '3'

services:
  fornax-db:
    image: postgres:10.4
    volumes:
      - fornaxdb:/var/lib/postgresql/data/
  fornax-web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
      - ~/.am/ss-location-data:/code/archivematica_transfer_source/
    ports:
      - "8003:8003"
    depends_on:
      - fornax-db

volumes:
  fornaxdb:
