version: '3'

services:
  fornax_db:
    image: postgres:10.4
  fornax_web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    depends_on:
      - fornax_db
