version: '3'

services:
  fornax_db:
    image: postgres:10.4
    volumes:
      - fornaxdb:/var/lib/postgresql/data/
  fornax_web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8003:8003"
    depends_on:
      - fornax_db

volumes:
  fornaxdb:
