# Generated by Django 2.0 on 2018-05-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RightsStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField(choices=[('Copyright', 'Copyright'), ('Statute', 'Statute'), ('License', 'License'), ('Other', 'Other')], max_length=64)),
                ('status', models.CharField(blank=True, choices=[('copyrighted', 'copyrighted'), ('public domain', 'public domain'), ('unknown', 'unknown')], max_length=64, null=True)),
                ('determination_date', models.DateField(blank=True, null=True)),
                ('jurisdiction', models.CharField(blank=True, max_length=2, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('terms', models.TextField(blank=True, null=True)),
                ('citation', models.TextField(blank=True, null=True)),
                ('note', models.TextField()),
                ('grant_act', models.CharField(choices=[('publish', 'Publish'), ('disseminate', 'Disseminate'), ('replicate', 'Replicate'), ('migrate', 'Migrate'), ('modify', 'Modify'), ('use', 'Use'), ('delete', 'Delete')], max_length=64)),
                ('grant_restriction', models.CharField(choices=[('allow', 'Allow'), ('disallow', 'Disallow'), ('conditional', 'Conditional')], max_length=64)),
                ('grant_start_date', models.DateField(blank=True, null=True)),
                ('grant_end_date', models.DateField(blank=True, null=True)),
                ('grant_note', models.TextField()),
                ('doc_id_role', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_id_type', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_id_value', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aurora_uri', models.URLField()),
                ('component_uri', models.URLField(blank=True, null=True)),
                ('process_status', models.CharField(choices=[(10, 'New transfer created'), (20, 'SIP files moved to processing'), (30, 'SIP validated according to BagIt'), (30, 'SIP restructured'), (40, 'PREMIS CSV rights added'), (50, 'Submission documentation added'), (60, 'bag-info.txt updated'), (70, 'Manifests updated'), (80, 'SIP validated'), (90, 'Delivered to Archivematica Transfer Source')], max_length=100)),
                ('bag_path', models.CharField(max_length=100)),
                ('bag_identifier', models.CharField(max_length=255, unique=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('modified_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='rightsstatement',
            name='sip',
            field=models.ForeignKey(on_delete='CASCADE', related_name='rights_statements', to='sip_assembly.SIP'),
        ),
    ]
