# Generated by Django 2.0 on 2018-09-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip_assembly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sip',
            name='process_status',
            field=models.CharField(choices=[(10, 'New SIP created'), (20, 'SIP files moved to processing'), (30, 'SIP validated according to BagIt'), (30, 'SIP restructured'), (40, 'PREMIS CSV rights added to SIP'), (50, 'Submission documentation added to SIP'), (60, 'SIP bag-info.txt updated'), (70, 'Archivematica processing config added'), (80, 'SIP Manifests updated'), (90, 'SIP Delivered to Archivematica Transfer Source')], max_length=100),
        ),
    ]
