# Generated by Django 2.0 on 2018-11-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip_assembly', '0002_auto_20180910_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sip',
            name='process_status',
            field=models.CharField(choices=[(10, 'New SIP created'), (20, 'SIP assembled and delivered to Archivematica'), (30, 'SIP started in Archivematica'), (40, 'SIP approved in Archivematica')], max_length=100),
        ),
    ]
