# Generated by Django 2.0 on 2018-11-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip_assembly', '0003_auto_20181112_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sip',
            name='process_status',
            field=models.CharField(
                choices=[
                    (10,
                     'New SIP created'),
                    (20,
                     'SIP assembled and delivered to Archivematica'),
                    (30,
                     'SIP started in Archivematica'),
                    (40,
                     'SIP approved in Archivematica'),
                    (50,
                     'SIP removed from src directory')],
                max_length=100),
        ),
    ]
