# Generated by Django 2.2.10 on 2020-03-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip_assembly', '0005_sip_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sip',
            name='type',
            field=models.CharField(blank=True, choices=[('aip', 'Archival Information Package'), ('dip', 'Dissemination Information Package')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sip',
            name='bag_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sip',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sip',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sip',
            name='process_status',
            field=models.IntegerField(),
        ),
    ]
