# Generated by Django 3.2.5 on 2021-07-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip_assembly', '0006_auto_20200317_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sip',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
