# Generated by Django 3.2.7 on 2021-10-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip_assembly', '0007_alter_sip_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sip',
            name='archivematica_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
